import {
  item1thumbnail,
  item1template,
  item2thumbnail,
  item2template,
  item3thumbnail,
  item3template,
  item4thumbnail,
  item4template,
  item5thumbnail,
  item5template,
  item6thumbnail,
  item6template,
  item7thumbnail,
  item7template,
  item8thumbnail,
  item8template,
  item9thumbnail,
  item9template,
  item10thumbnail,
  item10template,
  item11thumbnail,
  item11template,
  item12thumbnail,
  item12template,
  item13thumbnail,
  item13template,
  item14thumbnail,
  item14template,
  item15thumbnail,
  item15template,
  item16thumbnail,
  item16template,
} from '../public/images/clothTemplate'
import { profile1, profile2, profile3, profile4 } from '../public/svg/userProfile'
import { itemType } from '../types/type'

export const USER_NAMES = [
  'Ava',
  'Ann',
  'Jake',
  'Joseph',
  'Colin',
  'Emily',
  'Isaac',
  'Blake',
  'Harry',
]

export const ITEM_ARR: itemType[] = [
  {
    thumbnailPng: item1thumbnail,
    meshName: 'Tank004F',
    templatePng: item1template,
    title: 'Tank Top',
    price: 4,
    creator: 'Chloe',
    creatorProfilePng: profile4,
    quantity: 200000,
    offerValue: 100000,
  },
  {
    thumbnailPng: item2thumbnail,
    meshName: 'Backpack001',
    templatePng: item2template,
    title: 'Red Backpack',
    price: 5,
    creator: 'Jay',
    creatorProfilePng: profile3,
    quantity: 100000,
    offerValue: 120000,
  },
  {
    thumbnailPng: item3thumbnail,
    meshName: 'Backpack006',
    templatePng: item3template,
    title: 'Pink Backpack',
    price: 6,
    creator: 'Jay',
    creatorProfilePng: profile3,
    quantity: 300000,
    offerValue: 130000,
  },
  {
    thumbnailPng: item4thumbnail,
    meshName: 'Shoe001',
    templatePng: item4template,
    title: 'Silver Sack',
    price: 6,
    creator: 'Ann',
    creatorProfilePng: profile2,
    quantity: 50000,
    offerValue: 140000,
  },
  {
    thumbnailPng: item5thumbnail,
    meshName: 'Crop010F',
    templatePng: item5template,
    title: 'Crop shirt',
    price: 4,
    creator: 'Chloe',
    creatorProfilePng: profile4,
    quantity: 600000,
    offerValue: 170000,
  },
  {
    thumbnailPng: item6thumbnail,
    meshName: 'MTM003M',
    templatePng: item6template,
    title: 'Top MTM',
    price: 7,
    creator: 'Joy',
    creatorProfilePng: profile1,
    quantity: 30000,
    offerValue: 180000,
  },
  {
    thumbnailPng: item7thumbnail,
    meshName: 'HalfSkirt001',
    templatePng: item7template,
    title: 'Half Skirt',
    price: 5,
    creator: 'Ann',
    creatorProfilePng: profile2,
    quantity: 1000000,
    offerValue: 130000,
  },
  {
    thumbnailPng: item8thumbnail,
    meshName: 'Longskirt001',
    templatePng: item8template,
    title: 'Long Skirt',
    price: 7,
    creator: 'Jay',
    creatorProfilePng: profile3,
    quantity: 80000,
    offerValue: 180000,
  },
  {
    thumbnailPng: item9thumbnail,
    meshName: 'Jean006',
    templatePng: item9template,
    title: 'Jean',
    price: 7,
    creator: 'Joy',
    creatorProfilePng: profile1,
    quantity: 300000,
    offerValue: 180000,
  },
  {
    thumbnailPng: item10thumbnail,
    meshName: 'DefaultShorts001',
    templatePng: item10template,
    title: 'Shorts',
    price: 4,
    creator: 'Joy',
    creatorProfilePng: profile1,
    quantity: 150000,
    offerValue: 140000,
  },
  {
    thumbnailPng: item11thumbnail,
    meshName: 'Blouson001',
    templatePng: item11template,
    title: 'Blouson',
    price: 10,
    creator: 'Jay',
    creatorProfilePng: profile3,
    quantity: 270000,
    offerValue: 200000,
  },
  {
    thumbnailPng: item12thumbnail,
    meshName: 'Default005',
    templatePng: item12template,
    title: 'Socks',
    price: 3,
    creator: 'Chloe',
    creatorProfilePng: profile4,
    quantity: 180000,
    offerValue: 125000,
  },
  {
    thumbnailPng: item13thumbnail,
    meshName: 'DenimJacket001',
    templatePng: item13template,
    title: 'Denim Jacket',
    price: 3,
    creator: 'Joy',
    creatorProfilePng: profile1,
    quantity: 200000,
    offerValue: 100000,
  },
  {
    thumbnailPng: item14thumbnail,
    meshName: 'DoubleJacket002M',
    templatePng: item14template,
    title: 'Double Jacket',
    price: 5,
    creator: 'Jay',
    creatorProfilePng: profile3,
    quantity: 100000,
    offerValue: 120000,
  },
  {
    thumbnailPng: item15thumbnail,
    meshName: 'Skirt012',
    templatePng: item15template,
    title: 'Purple Check Skirt',
    price: 6,
    creator: 'Jay',
    creatorProfilePng: profile3,
    quantity: 300000,
    offerValue: 130000,
  },
  {
    thumbnailPng: item16thumbnail,
    meshName: 'Track001',
    templatePng: item16template,
    title: 'Track Pants',
    price: 6,
    creator: 'Ann',
    creatorProfilePng: profile2,
    quantity: 50000,
    offerValue: 140000,
  },
]

export const LIVE_LIST = [
  { user: 1, thumbnail: 4 },
  { user: 2, thumbnail: 2 },
  { user: 3, thumbnail: 1 },
  { user: 2, thumbnail: 6 },
  { user: 3, thumbnail: 8 },
  { user: 1, thumbnail: 2 },
  { user: 1, thumbnail: 11 },
  { user: 4, thumbnail: 5 },
  { user: 1, thumbnail: 7 },
  { user: 1, thumbnail: 6 },
  { user: 4, thumbnail: 9 },
  { user: 2, thumbnail: 15 },
  { user: 2, thumbnail: 13 },
]

export const INITIAL_NFT_INFO = {
  thumbnail: '',
  title: '',
  history: [],
  details: {
    'Contract Address': '0x72f223423984723649823782374982392e9',
    'Mint Hash': '',
    'Token ID': '',
    'Token Standard': 'ERC-721',
    Chain: 'Settlus',
    Creator: '',
    Owner: '',
  },
  revenue: {
    Price: 0,
    Quantity: 0,
  },
}
